"""empty message

Revision ID: 52f7c3c01ef6
Revises: 9f46c48bbadc
Create Date: 2022-02-25 18:21:10.907880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f7c3c01ef6'
down_revision = '9f46c48bbadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_domain_sha256'), 'domain', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_sha256'), table_name='domain')
    # ### end Alembic commands ###
