"""empty message

Revision ID: 6e5ed2add0a3
Revises: 884cdb857b24
Create Date: 2021-07-07 21:35:06.793448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5ed2add0a3'
down_revision = '884cdb857b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
