"""empty message

Revision ID: 83e5a45a34b6
Revises: f191972c4f07
Create Date: 2022-02-25 17:55:27.879337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e5a45a34b6'
down_revision = 'f191972c4f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('domain', sa.Text(), nullable=False))
    op.drop_column('domain', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('domain', 'domain')
    # ### end Alembic commands ###
