"""empty message

Revision ID: 884cdb857b24
Revises: 
Create Date: 2021-06-27 14:37:10.161563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884cdb857b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
