"""empty message

Revision ID: 9f46c48bbadc
Revises: 83e5a45a34b6
Create Date: 2022-02-25 18:13:20.929006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f46c48bbadc'
down_revision = '83e5a45a34b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
