"""empty message

Revision ID: f191972c4f07
Revises: 1a1615f8ca14
Create Date: 2022-02-25 17:43:05.406812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f191972c4f07'
down_revision = '1a1615f8ca14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.create_unique_constraint(None, 'domain', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domain', type_='unique')
    op.create_table('post',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('modify_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='post_pkey'),
    sa.UniqueConstraint('id', name='post_id_key')
    )
    # ### end Alembic commands ###
